services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: healthcare_backend
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
    env_file:
      - ./backend/.env.docker
    environment:
      - NODE_EXTRA_CA_CERTS=/etc/ssl/certs/aws-rds-global-bundle.pem
    volumes:
      - /home/ubuntu/certs/aws-rds-global-bundle.pem:/etc/ssl/certs/aws-rds-global-bundle.pem:ro
